server {
    listen 80;
    listen [::]:80;
    # URL temporaneo finché il DNS non punta al server
    listen 8090;
    listen [::]:8090;
    server_name planner.percorsisolari.it;

    root /opt/digital-planner/out;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    location /_next/static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        expires 30d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ $uri.html /404.html;
    }

    error_page 404 /404.html;
}
